"""Controlled provenance vocabulary used by every model input and output."""

from enum import StrEnum


class OriginClass(StrEnum):
    REPORTED_DIRECT = "REPORTED_DIRECT"
    REPORTED_INHERITED = "REPORTED_INHERITED"
    DONOR_POOL = "DONOR_POOL"
    USER_INPUT = "USER_INPUT"
    MODEL_INFERRED = "MODEL_INFERRED"
    SYNTHETIC_SCENARIO = "SYNTHETIC_SCENARIO"


class TransformationClass(StrEnum):
    NONE = "NONE"
    UNIT_CONVERSION = "UNIT_CONVERSION"
    PARAMETER_MAPPING = "PARAMETER_MAPPING"
    EQUATION_APPLICATION = "EQUATION_APPLICATION"
    DISTRIBUTION_FITTING = "DISTRIBUTION_FITTING"
    CATEGORICAL_HARMONIZATION = "CATEGORICAL_HARMONIZATION"
    IMPUTATION = "IMPUTATION"
    SCENARIO_GENERATION = "SCENARIO_GENERATION"


class ReviewState(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    SYSTEM_NORMALIZED = "SYSTEM_NORMALIZED"
    USER_REVIEW_REQUIRED = "USER_REVIEW_REQUIRED"
    USER_APPROVED = "USER_APPROVED"
    USER_REJECTED = "USER_REJECTED"
