import csv, sys
sys.stdout.reconfigure(encoding="utf-8")

H = ["study_id","citation","doi","pmid","pmcid","open_access","license","population","n_subjects",
     "infusion_mode","anonymised_patient_id","concentration_observations","sampling_times",
     "dose_history","infusion_start_stop","plasma_conc","elf_conc","renal_function","body_weight",
     "age_sex","rrt_ecmo_status","mic_data","isolate_info","blq_observations","assay_error_lloq",
     "clinical_outcomes","model_code","model_files_nonmem_monolix","covariance_matrix",
     "supplementary_individual_profiles","public_repository","data_availability_statement",
     "corresponding_author_route","classification","evidence_and_url"]

def row(**k):
    return [k.get(c, "NOT ASSESSED") for c in H]

R = [
 row(study_id="S1_Cojutti2024",
     citation="Cojutti PG, Pai MP, Gatti M, et al. J Antimicrob Chemother 2024;79(11):2801-8",
     doi="10.1093/jac/dkae290", pmid="39159014", pmcid="NONE",
     open_access="NO - closed", license="All rights reserved (OUP/BSAC)",
     population="Critically ill adults, ICU Bologna, CPE infections, non-RRT", n_subjects="112",
     infusion_mode="Continuous infusion, median 2.5 g q8h",
     anonymised_patient_id="NO - Table 1 is aggregate only (medians, IQR, counts)",
     concentration_observations="NO - 185 steady-state concentrations reported only as cohort medians",
     sampling_times="NO - described as 48-72 h after start, then ad hoc; no per-sample times",
     dose_history="NO - median dose only", infusion_start_stop="NO",
     plasma_conc="NO - aggregate only (CAZ fCss 42.3 [27.0-73.5]; AVI fCss 9.5 [5.1-15.7] mg/L)",
     elf_conc="NOT APPLICABLE - no ELF sampling",
     renal_function="NO - aggregate only (eGFR median 92, IQR 50-113 mL/min/1.73 m2)",
     body_weight="NO - aggregate only (74 kg, 45-106)",
     age_sex="NO - aggregate only (64 y, 31-80; M/F 70/42)",
     rrt_ecmo_status="Cohort described as non-RRT", mic_data="NO per-isolate MIC published",
     isolate_info="Aggregate: KPC- and OXA-48-producing Enterobacterales",
     blq_observations="NOT REPORTED", assay_error_lloq="LC-MS/MS stated as validated; no LLOQ given",
     clinical_outcomes="Aggregate only", model_code="NOT PROVIDED",
     model_files_nonmem_monolix="NOT PROVIDED (Monolix 2023R1 named; no .mlxtran)",
     covariance_matrix="YES - FULLY SPECIFIED. IIV on CL_CAZ and CL_AVI only; the single off-diagonal correlation 0.94 (RSE 23.8%) is published in Table 2",
     supplementary_individual_profiles="Figures S2-S6 are model diagnostic plots containing individual points, but PAYWALLED; figure-point digitisation only",
     public_repository="NONE FOUND",
     data_availability_statement="ABSENT - the article carries no data availability statement of any kind",
     corresponding_author_route="Manjunath P. Pai, ORCID 0000-0001-7119-5034; email obfuscated on the publisher page, decodes to amitpai@med.umich.edu (inferred by decoding, not read verbatim). Milo Gatti / Federico Pea are co-authors and are reachable at milo.gatti2@unibo.it",
     classification="F (not suitable for model development or validation) / E (data potentially available by author request)",
     evidence_and_url="https://academic.oup.com/jac/article/79/11/2801/7736048 ; Unpaywall is_oa=false, oa_locations=[] ; Europe PMC hasSuppl=N. ALL SEVEN PK PARAMETERS USED BY THIS PROJECT WERE INDEPENDENTLY CONFIRMED AGAINST TABLE 2. Table 4 is the real 9 regimens x 8 MIC = 72-cell PTA benchmark."),

 row(study_id="S2_Gatti2023",
     citation="Gatti M, Rinaldi M, Gaibani P, et al. J Crit Care 2023;76:154301",
     doi="10.1016/j.jcrc.2023.154301", pmid="37059003", pmcid="NONE",
     open_access="YES - hybrid", license="CC BY-NC-ND 4.0",
     population="Critically ill adults undergoing CVVHDF, DTR Gram-negative infections", n_subjects="8 patients, 17 TDM occasions",
     infusion_mode="Continuous infusion 2.5 g q8h over 8 h, reduced to 1.25 g q8h in 6 of 8; 2.5 g loading dose over 2 h",
     anonymised_patient_id="YES - case IDs #1 to #8 in both tables",
     concentration_observations="YES (derived) - average free Css per patient in Table 1; total clearance per TDM occasion in Table 2",
     sampling_times="PARTIAL - occasions are ordered and dose-flagged, but no clock times",
     dose_history="YES - initial dose, adjustment, and the dose in force at each occasion",
     infusion_start_stop="NOT APPLICABLE - continuous infusion at steady state",
     plasma_conc="YES - average free Css for ceftazidime and avibactam, per patient",
     elf_conc="NOT APPLICABLE - no ELF sampling",
     renal_function="PARTIAL - residual diuresis per occasion; CVVHDF dose intensity per occasion; no serum creatinine",
     body_weight="YES - per patient, in Table 2",
     age_sex="YES - per patient, in Table 1",
     rrt_ecmo_status="YES - all on CVVHDF, with full circuit settings per occasion",
     mic_data="YES - per-patient MIC (1 to 8 mg/L)",
     isolate_info="YES - per-patient pathogen and resistance mechanism",
     blq_observations="NONE reported", assay_error_lloq="Validated LC-MS/MS; no LLOQ given",
     clinical_outcomes="YES - per patient: microbiological eradication, treatment duration, 30-day mortality",
     model_code="NOT APPLICABLE - descriptive analysis, no population PK model",
     model_files_nonmem_monolix="NOT APPLICABLE",
     covariance_matrix="NOT APPLICABLE - no mixed-effects model fitted",
     supplementary_individual_profiles="NONE - but Figure 1 plots the same 17 pairs already printed in Table 2, so no digitisation is needed",
     public_repository="Version of Record PDF freely downloadable from the University of Bologna repository, https://cris.unibo.it/handle/11585/929418",
     data_availability_statement="ABSENT - but moot, because the data are printed in the tables",
     corresponding_author_route="Milo Gatti, milo.gatti2@unibo.it (printed in the article)",
     classification="C (suitable for sensitivity and assumption-testing analysis only) - NOT B, because the population is CVVHDF and the primary scenario excludes RRT",
     evidence_and_url="https://cris.unibo.it/handle/11585/929418 ; file 1-s2.0-S0883944123000503-main.pdf. TRANSCRIBED TO model_development_v18/data_external/. Transcription verified: recomputed CL medians and IQRs reproduce the authors' reported 2.39 (2.05-2.94) and 2.56 (2.22-2.96) L/h EXACTLY."),

 row(study_id="S3_BenitezCano2026",
     citation="Benitez-Cano A, Sancho-Araiz A, Carazo J, et al. Crit Care 2026;30:305",
     doi="10.1186/s13054-026-06075-w", pmid="42129898", pmcid="PMC13262505",
     open_access="YES", license="CC BY-NC-ND",
     population="Critically ill adults, nosocomial pneumonia, surgical ICU Barcelona; RRT and ECMO were exclusion criteria",
     n_subjects="30 randomised; 15 in the ceftazidime-avibactam arm",
     infusion_mode="Loading dose 2 g/0.5 g over 120 min, then 2 g/0.5 g q8h infused over 8 h (6 g/1.5 g per day)",
     anonymised_patient_id="PARTIAL - subject IDs 1-30 appear as panel headings in Supplementary Figures S3.3 and S3.4, but only as figure labels",
     concentration_observations="NO NUMERIC DATA. 74 plasma observations per analyte and 14 ELF observations per analyte are stated, but published only as median (IQR) at four nominal times",
     sampling_times="Design times only: end of loading dose, then 1, 4 and 8 h; ELF at 1, 4 or 8 h on days 3-4",
     dose_history="Protocol dose only; renal adjustment permitted on day 3 after sampling",
     infusion_start_stop="NO",
     plasma_conc="AGGREGATE ONLY - Supplementary Table S2 gives median (IQR) at each nominal time; AUC(0-8,ss) medians in the main text",
     elf_conc="AGGREGATE ONLY - ELF Css median (IQR) 45.2 [24.2] mg/L ceftazidime, 4.1 [3.4] mg/L avibactam",
     renal_function="AGGREGATE ONLY - CKD-EPI, arm median 63.0 mL/min/1.73 m2",
     body_weight="AGGREGATE ONLY - arm median 74.0 kg",
     age_sex="AGGREGATE ONLY - arm median 77 y; 1 of 15 female",
     rrt_ecmo_status="UNIFORMLY ABSENT BY DESIGN - both were exclusion criteria",
     mic_data="NO per-isolate MIC published; Vitek2 with EUCAST breakpoints; 6 of 15 culture-positive",
     isolate_info="Aggregate only; no DTR or carbapenemase-producing Enterobacterales",
     blq_observations="NOT REPORTED - no censoring method stated anywhere",
     assay_error_lloq="YES - ceftazidime plasma LLOQ 2.5 mg/L (BAL 0.25-10); avibactam plasma LLOQ 0.1 mg/L (BAL 0.005-5); proportional residual error 0.27 and 0.32",
     clinical_outcomes="Aggregate only; not powered for clinical outcomes",
     model_code="NOT PROVIDED - no .mlxtran, no project file, no script",
     model_files_nonmem_monolix="NOT PROVIDED (Monolix 2019R1 and Simulx named)",
     covariance_matrix="NO - RSE% only; no variance-covariance matrix, no CIs, no bootstrap",
     supplementary_individual_profiles="YES BUT GRAPHICAL ONLY - Supplementary Figures S3.3 and S3.4 give per-patient plasma and ELF panels headed by subject ID, on LOGARITHMIC axes with sparse gridlines; digitisation would carry material error and could not recover exact times or ELF sampling bin",
     public_repository="NONE - full-text and supplement searches for repository, github, zenodo, figshare returned nothing",
     data_availability_statement="PRESENT: 'The datasets used and analyzed during the current study are available from the corresponding author on reasonable request.'",
     corresponding_author_route="Luisa Sorli, lsorli@hmar.cat (printed in the affiliation footnotes)",
     classification="E (data potentially available by author request) / D (aggregate evidence only, as currently published)",
     evidence_and_url="https://pmc.ncbi.nlm.nih.gov/articles/PMC13262505/ ; all three supplementary .docx files retrieved from static-content.springer.com and read in full. NOTE Supplementary Table S3.1 is titled 'Individual observed and predicted...' but every cell is a median (IQR) across patients - it is NOT individual data. THREE DIFFERENT ELF/plasma ratio pairs are published: median individual AUC ratios 0.41/0.44 (the pair this manuscript uses), model-based EPR 0.51/0.60, and S3.1 observed 0.46/0.40."),

 row(study_id="S4_Dimelow2018",
     citation="Dimelow R, Wright JG, MacPherson M, Newell P, Das S. Drugs R D 2018;18(3):221-30",
     doi="10.1007/s40268-018-0241-0", pmid="30054895", pmcid="PMC6131119",
     open_access="YES", license="CC BY-NC 4.0",
     population="Healthy male volunteers - NOT critically ill", n_subjects="43 enrolled, 42 with PK data",
     infusion_mode="2-hour intermittent IV q8h for 3 days - NOT continuous infusion",
     anonymised_patient_id="NO", concentration_observations="NO - no per-subject table anywhere",
     sampling_times="NOT REPORTED in this paper (they reside in the primary phase 1 report)",
     dose_history="Protocol only: 2000/500 mg or 3000/1000 mg, nine doses",
     infusion_start_stop="NO", plasma_conc="NO - figure points only (prediction-corrected VPC)",
     elf_conc="NO - one BAL sample per subject; residual error on ELF had to be FIXED because it could not be estimated",
     renal_function="Healthy volunteers; not tabulated per subject", body_weight="NO", age_sex="All male; ages not per subject",
     rrt_ecmo_status="NOT APPLICABLE", mic_data="NOT APPLICABLE", isolate_info="NOT APPLICABLE",
     blq_observations="NOT REPORTED", assay_error_lloq="Proportional residual error 0.101 (CAZ) and 0.117 (AVI)",
     clinical_outcomes="NOT APPLICABLE", model_code="NOT PROVIDED",
     model_files_nonmem_monolix="NOT PROVIDED (NONMEM 7.2.0 named)",
     covariance_matrix="STATED BUT NOT REPORTED - 'a full covariance matrix' was estimated, yet only diagonal CV% values are printed. The off-diagonals are NOT recoverable.",
     supplementary_individual_profiles="NONE - no electronic supplementary material at all",
     public_repository="Underlying trial NCT01395420 has has_results=false; no participant data posted",
     data_availability_statement="PRESENT - Pfizer controlled-access process, https://www.pfizer.com/science/clinical-trials/trial-data-and-results",
     corresponding_author_route="Shampa Das, shampa.das@liverpool.ac.uk (from PubMed metadata, not printed in the article body)",
     classification="D (aggregate evidence only) / E (individual data available via the Pfizer controlled-access route, subject to criteria and a 24-month window)",
     evidence_and_url="https://pmc.ncbi.nlm.nih.gov/articles/PMC6131119/ . This is the ORIGIN of the 0.85/0.92 unbound fractions used throughout the project. Structural model is THREE-compartment and PK/PD targets are 50%fT>8 and 50%fT>1 mg/L - not interchangeable with the continuous-infusion targets used here."),

 row(study_id="S5_OJeanson2025",
     citation="O'Jeanson A, Nielsen EI, Friberg LE. J Antimicrob Chemother 2025;80(1):79-86",
     doi="10.1093/jac/dkae375", pmid="NOT ASSESSED", pmcid="NOT ASSESSED",
     open_access="NOT ASSESSED", license="NOT ASSESSED",
     population="Simulation study of beta-lactam / beta-lactamase inhibitor TDM", n_subjects="Simulated, not observed",
     infusion_mode="Various", anonymised_patient_id="NOT APPLICABLE - simulation study",
     concentration_observations="NOT APPLICABLE - no observed patients",
     sampling_times="NOT APPLICABLE", dose_history="NOT APPLICABLE", infusion_start_stop="NOT APPLICABLE",
     plasma_conc="NOT APPLICABLE", elf_conc="NOT APPLICABLE", renal_function="NOT APPLICABLE",
     body_weight="NOT APPLICABLE", age_sex="NOT APPLICABLE", rrt_ecmo_status="NOT APPLICABLE",
     mic_data="NOT APPLICABLE", isolate_info="NOT APPLICABLE", blq_observations="NOT APPLICABLE",
     assay_error_lloq="NOT APPLICABLE", clinical_outcomes="NOT APPLICABLE",
     model_code="NOT ASSESSED", model_files_nonmem_monolix="NOT ASSESSED", covariance_matrix="NOT ASSESSED",
     supplementary_individual_profiles="NOT APPLICABLE", public_repository="NOT ASSESSED",
     data_availability_statement="NOT ASSESSED", corresponding_author_route="Lena E. Friberg, Uppsala University",
     classification="F (not suitable - contains no patient-level data by design)",
     evidence_and_url="Used in this project only as a donor input for sensitivity analyses. A simulation study cannot supply observed data."),

 row(study_id="S6_Curtiaud2024",
     citation="Curtiaud A, Petit M, Chommeloux J, et al. J Antimicrob Chemother 2024;79(5):1182-6",
     doi="10.1093/jac/dkae091", pmid="NOT ASSESSED", pmcid="NOT ASSESSED",
     open_access="NOT ASSESSED", license="NOT ASSESSED",
     population="Adults on ECMO", n_subjects="NOT ASSESSED", infusion_mode="NOT ASSESSED",
     anonymised_patient_id="NOT ASSESSED", concentration_observations="NOT ASSESSED",
     sampling_times="NOT ASSESSED", dose_history="NOT ASSESSED", infusion_start_stop="NOT ASSESSED",
     plasma_conc="NOT ASSESSED", elf_conc="NOT APPLICABLE", renal_function="NOT ASSESSED",
     body_weight="NOT ASSESSED", age_sex="NOT ASSESSED", rrt_ecmo_status="ECMO cohort",
     mic_data="NOT ASSESSED", isolate_info="NOT ASSESSED", blq_observations="NOT ASSESSED",
     assay_error_lloq="NOT ASSESSED", clinical_outcomes="NOT ASSESSED", model_code="NOT ASSESSED",
     model_files_nonmem_monolix="NOT ASSESSED", covariance_matrix="NOT ASSESSED",
     supplementary_individual_profiles="NOT ASSESSED", public_repository="NOT ASSESSED",
     data_availability_statement="NOT ASSESSED", corresponding_author_route="NOT ASSESSED",
     classification="NOT ASSESSED - out of scope for the primary non-RRT, non-ECMO scenario",
     evidence_and_url="Used in this project only as a contextual PK anchor; contributes no numerical input to the primary model (Supplementary Table S2a). Full assessment deferred as out of scope."),
]

with open("DATA_AVAILABILITY_MATRIX.csv", "w", newline="", encoding="utf-8") as fh:
    w = csv.writer(fh, lineterminator="\n")
    w.writerow(H)
    w.writerows(R)

print(f"wrote {len(R)} studies x {len(H)} fields")
for r in R:
    print(f"  {r[0]:22} -> {r[H.index('classification')]}")
